### ISSUE TITLE
 The custom integration 'rika_firenet' does not have a valid version key (None) in the manifest file and was blocked from loading

### ISSUE THREAD

**Issue by cobwash** [Fockaert/rika-firenet-custom-component#14]
at some recent point, a new key was made a requirement in the manifest file.

I've manually updated mine to "version": "0.0.1" which has allowed it to proceed. 
![image](https://user-images.githubusercontent.com/86403356/125928889-603380f0-cd1e-4258-889a-b10a9bac5ef1.png)

**Comment by cobwash** [comment]
my current updated manifest which is working as at today
![image](https://user-images.githubusercontent.com/86403356/126032799-d76bca47-5da1-4efd-9be7-537229fa2f0f.png)

**Comment by NoMoreInfo** [comment]
not working for me. I had the integration work for some times and it "suddenly" stopped. I removed the integration, changed the manifest file and now I am failing to add the integration, again. Not appearing in Integrations. Restarted a few times. Any idea?

**Comment by Fockaert** [comment]
The version property is indeed missing, similar like forum post https://community.home-assistant.io/t/no-version-key-in-the-manifest-file-for-custom-integration-ha-2021-3-0/286487

I'll add it to manifest file, locally it works again manually.

**Comment by Fockaert** [comment]
Version key added, please try again whether this is fixed.

**Comment by cobwash** [comment]
the manifest file now allows me to start the config_flow with a fresh download. (cleared old version from custom_components, restarted HA and reinstalled from a fresh zip download).
