### ISSUE TITLE
Home assistant core-2021.11.0 support

### ISSUE THREAD

**Issue by edillmann** [Fockaert/rika-firenet-custom-component#17]
Hi,

I just tried your component on HA core-2021.11.0, it's working but present as many devices as there are sensors in my stove.

I think the sensors should be under only one device.

Thanks

**Comment by LarrxX** [comment]
I'm having the same problem with core-2021.11.5

**Comment by pafsan** [comment]
Hello, same problem with core-2022.2.1
If you need me for testing, i can help.
I have a rika sono
Thks for your job, regards

**Comment by tuxtof** [comment]
@pafsan @LarrxX @edillmann 

check the fork here it is fixed
https://github.com/antibill51/rika-firenet-custom-component

**Comment by Fockaert** [comment]
Thx @tuxtof , did your following commit fix this https://github.com/Fockaert/rika-firenet-custom-component/commit/5f8d12a059ccb40932098af04459d3c133fce490 ?
