### ISSUE TITLE
deprecated methods on an instance of NumberEntity

### ISSUE THREAD

**Issue by qbushome** [Fockaert/rika-firenet-custom-component#18]
Hi

After upgrading to HA 2022.7 I saw this error/warning in the logs:

`Logger: homeassistant.components.number
Source: components/number/__init__.py:220
Integration: Nummer ([documentation](https://www.home-assistant.io/integrations/number), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+number%22))
First occurred: 13:36:14 (1 occurrences)
Last logged: 13:36:14

custom_components.rika_firenet.number::RikaFirenetStoveNumber is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom component author.`

Would you be so kind to take a look at this so we don't have issues during the heating-season ?

Thank you

**Comment by Fockaert** [comment]
Hi @qbushome , 

I'll take a look.

Thanks,
Jan

**Comment by Fockaert** [comment]
Tested the fix locally and no warnings popped up, closing issue.
