### ISSUE TITLE
On off switch and power slider

### ISSUE THREAD

**Issue by qbushome** [Fockaert/rika-firenet-custom-component#8]
On the rika-firenet website I’m able to switch on/off the stove and also change the power (between 30% and 100%).

It would be great if a switch can be added for turning on or off the stove ( now the sensor only reflects it status).
Forcing the stove off to schedule a cleaning interval is a possible use-case.

Also  a slider (like you have brightness for a light) but then limited between 30 and 100%, that's what the limitations of the firmware are, below 30% is just not possible.
Depending on the outdoor temperature one could select a higher power% to keep up with room temperature that lowers faster than on warmer days.

Great component !

**Comment by Fockaert** [comment]
Duplicate with #7
